#!/usr/bin/env python3
"""Regenerates Sources/GaterCore/Hooks/Templates.swift from the canonical
files in claude/. TemplatesTests fails if they drift; run this to fix."""
import os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def read(rel):
    with open(os.path.join(root, rel)) as f:
        return f.read()

def literal(s):
    # Raw multi-line literal. Swift drops the newline right before the
    # closing delimiter, so add one to keep the file's trailing newline.
    assert '"""#' not in s
    return '#"""\n' + s + '\n"""#'

skill = read("claude/skills/gater-delegate/SKILL.md")
hook = read("claude/git-hooks/prepare-commit-msg")

swift = f'''import Foundation

// GENERATED by scripts/gen-templates.py from claude/ — do not edit by hand.

/// Files Gater writes into target repositories. The canonical copies live
/// in claude/ at the root of this repo (spec §5 layout); these embedded
/// versions are what gets installed, and TemplatesTests fails if the two
/// ever drift.
public enum Templates {{
    /// claude/skills/gater-delegate/SKILL.md
    public static let delegationSkill = {literal(skill)}

    /// claude/git-hooks/prepare-commit-msg, with @GATER_HOOK@ standing in
    /// for the absolute path of the gater-hook binary.
    public static let prepareCommitMsg = {literal(hook)}

    static let hookPlaceholder = "@GATER_HOOK@"
    static let gitHookMarker = "# gater-managed"
}}
'''
with open(os.path.join(root, "Sources/GaterCore/Hooks/Templates.swift"), "w") as f:
    f.write(swift)
